[package]
name = "formatcls"
version = "0.1.1"
authors = ["puripuri2100 <puripuri2100@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.20.3"
serde_json = "1.0.48"
json-patch = "*"